### PR TITLE
Use power and energy density instead irradiance and irradiation

### LINKED ISSUE #244: Keep `PowerDensity` and `EnergyDensity` instead of `Irradiation` and `Irradiance`
As these are more generic and can and their units e.g. Watt/m^2 can and will be used in other contexts. For example for average power of a household in Osmogrid.

### PR DESCRIPTION
**Pull request by t-ober**
resolves  #244

### CODE REVIEW

**Review by johanneshiry — CHANGES_REQUESTED** [review]
No. Because power and energy density are actually different units according to the SI unit standard! 

See references of [power density](https://en.wikipedia.org/wiki/Power_density#:~:text=Power%20density%20is%20the%20amount,expressed%20as%20W%2Fm3.) and [energy density](https://en.wikipedia.org/wiki/Energy_density#:~:text=In%20physics%2C%20energy%20density%20is,(or%20gravimetric%20energy%20density).) for details!

**Comment by johanneshiry** [comment]
Additional comment: no issue here with the re-introducation of power and energy density but we may consider using the correct units then :)

**Comment by t-ober** [comment]
> No. Because power and energy density are actually different units according to the SI unit specification
> 
> Power density is defined as `amount of power (time rate of energy transfer) per unit volume` and energy density is defined as `amount of energy stored in a given system or region of space per unit volume`. So it's actually _not_ squared but cubed (m^3)!
> 
> See references of [power density](https://en.wikipedia.org/wiki/Power_density#:~:text=Power%20density%20is%20the%20amount,expressed%20as%20W%2Fm3.) and [energy density](https://en.wikipedia.org/wiki/Energy_density#:~:text=In%20physics%2C%20energy%20density%20is,(or%20gravimetric%20energy%20density).) for details.

Oh you are right! Note to self: Double check definitions! 😂  I was just assuming they mean the right thing since they were used before.
So for Irradiance one could use [surface power density](https://en.wikipedia.org/wiki/Surface_power_density) instead though I don't find a generic term for energy per unit of area.

**Comment by johanneshiry** [comment]
Lets discuss this for documentation purposes in the corresponding issue #244

**Pull request closed without merging**
