### PR TITLE
unit symbols to DIN 1301-1 for PowerSystemUnits

### LINKED ISSUE #278: Unit symbols according to DIN 1301 Teil1

### PR DESCRIPTION
**Pull request by danielfeismann**
resolves #278

### CODE REVIEW

**Review by sebastian-peter — APPROVED** [review]
Looks all good to me, thanks for this PR!

I noticed that not all units are registered with `addUnit`, thus parsing these quantities from Strings does not work. BUT, this shall be solved in a separate PR: #280 :)

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Maybe I was a bit quick with my approval. I just noticed there are different definitions of "per unit": `PU` and `p.u.`
Does a standardized naming exist here as well? If not, we should at least provide _some_ unified definition here.

**Comment by danielfeismann** [comment]
> Maybe I was a bit quick with my approval. I just noticed there are different definitions of "per unit": `PU` and `p.u.` Does a standardized naming exist here as well? If not, we should at least provide _some_ unified definition here.

I did not find anything on this. Personally I would prefer `p.u. ` and also this follows the rule of lowercase when it's not dedicated to a person (and isn't a liter :))

**Review by sebastian-peter — APPROVED** [review]
Thanks!

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
I just noticed that an addition to the changelog is still missing :) Would be great if you could supply that

**Review by sebastian-peter — APPROVED** [review]
Thanks a lot!

**Pull request merged**
