### PR TITLE
Set dependency version to fixed version

### LINKED ISSUE #79: Fix dependency versions

### PR DESCRIPTION
**Pull request by ckittl**
Closes #79. Close #78 before.

### CODE REVIEW

**Comment by johanneshiry** [comment]
pls let me know again when it's up for review

**Comment by johanneshiry** [comment]
Pls also add the changes you introduce here as well as the changes from #78 to the CHANGELOG.MD - I missed pointed this out in the last review and just approved it 😅

**Comment by ckittl** [comment]
> pls let me know again when it's up for review

Please feel notified. :grin:

**Review by johanneshiry — APPROVED** [review]
A good PR - thank you very much!

**Pull request merged**
